# Generated by Django 3.0.6 on 2020-05-10 20:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200509_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videos',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
