# Generated by Django 3.0.6 on 2020-05-14 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_auto_20200514_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Publihsed', 'Publihsed')], default='Draft', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Published', max_length=264, unique_for_date='Publihsed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
