# Generated by Django 3.0.6 on 2020-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Status',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Publihsed', 'Publihsed')], default='Draft', max_length=9),
        ),
    ]
