# Generated by Django 3.0.6 on 2020-05-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20200527_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
