# Generated by Django 3.0.6 on 2020-05-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
