# Generated by Django 3.0.6 on 2020-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_auto_20200528_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='DEFAULT', upload_to='profile_pic'),
        ),
    ]
