# Generated by Django 3.0.6 on 2020-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_auto_20200528_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile_pic'),
        ),
    ]
